name: build-gh-pages

on:
  push:
    branches:
      - main
      - master

defaults:
  run:
    shell: bash

jobs:
  build-gh-pages:
    name: ${{ matrix.command }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - run: yarn install

      - name: Build core
        run: yarn tsc -p tsconfig.web.json && bundle:web

      - name: Push build to gh-pages branch
        run: |
          git config --global user.name "desi-ivanov bot"
          git config --global user.email "desi-ivanov-bot@users.noreply.github.com'"
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/desi-ivanov/tsgrad --depth 1 --branch gh-pages gh-pages
          cd gh-pages
          git rm -rf .
          mkdir out
          cp -r ../out/* ./out
          cp ../index.html .
          git add -A
          git commit -m "Update gh-pages"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/desi-ivanov/tsgrad
          git push origin gh-pages%